### ISSUE TITLE
I would love to understand the purpuse of this repository

### ISSUE THREAD

**Issue by fosils** [aanari/pg-materialize#1]
What is the problem it is solving? I have lots of dependency problems currently.

**Comment by aanari** [comment]
Hi @fosils,

The purpose of this repository is to identify dependencies between views, by scanning and analyzing all of the scripts you have in a folder, and then generate a dependency graph and output scripts for how to run your scripts in the correct order. Currently it only supports Postgres and reading the scripts from a file system, but I would like to support applying changes to the database directly through a live connection as well.

What kinds of problems are you trying to solve with your dependencies?
